export const ActionTypes = {
    FEATCH_ALL: 'FEATCH_ALL',
    FEATCH_CATS: 'FEATCH_CATS',
    FEATCH_ONE: 'FEATCH_ONE',
    FEATCH_ONE_CAT: 'FEATCH_ONE_CAT',
    FEATCH_SEARCH: 'FEATCH_SEARCH',
    ADD_TO_FAV: 'ADD_TO_FAV',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REMOVE_FROM_FAV: 'REMOVE_FROM_FAV'

};

